export const STATIC_MAP = [
  'WWWWWWWWWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWWWWWWWWW',
  'WWWWFWWFFFWFFFWFFFWFWW',
  'WWWWFWWFFFWFFFWFFFWFWW',
  'WWWWFWWFFFWFFFWFFFWFWW',
  'WWWWFWWFFFWFFFWFFFWFWW',
  'WWWWWWWWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWWWWWWWWWW',
];
// W = Wheatfield, W = Wiver (1WaterCell), F = Forest (Trees trên Wheatfield) 