export const STATIC_MAP = [
  'WWWWWWWWWWWWWWWWWWWWWWWW',
  'WWRRRRRRRRRRRRRRRRRRRWW',
  'WWRWWWWWWWWWWWWWWWWWRWW',
  'WWRWFWWFFFWFFFWFFFWFWW',
  'WWRWFWWFFFWFFFWFFFWFWW',
  'WWRWFWWFFFWFFFWFFFWFWW',
  'WWRWFWWFFFWFFFWFFFWFWW',
  'WWRWWWWWWWWWWWWWWWWWRWW',
  'WWRRRRRRRRRRRRRRRRRRRWW',
  'WWWWWWWWWWWWWWWWWWWWWWWW',
];
// W = Wheatfield, R = River (1WaterCell), F = Forest (Trees trên Wheatfield) 